import cc.ControlCenter;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;

/**
 * Main class for the simulation of an harvest in an agricultural farm.
 * The workflow goes as follows:
 * 1. Create Control Center(this process is allocated to the Control Center)
 * 2. Create Farming Infrastructure as a new and independent process.
 * @author Filipe Pires (85122) and João Alegria (85048)
 */
public class Main {

    /**
     * Function responsible for initializing the simulation.
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        
        /*Launch Control Center UI*/
        System.out.println("[CC] Initializing Control Center... ");
        ControlCenter mainFrame = new ControlCenter();
        mainFrame.setVisible(true);
        
        /* Launch Farm Infrastructure */
        try {
            runProcess("java -cp " + System.getProperty("user.dir") + "/build/classes fi.FarmInfrastructure");
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * Executes other independent processes. 
     * @param command string containing the command line to execute
     * @throws Exception in case of some error occurs during the process execution phase and stream fetching
     */
    private static void runProcess(String command) throws Exception {
        Process proc = Runtime.getRuntime().exec(command);
        printLines("[FI]", proc.getInputStream());
        printLines("[FI]", proc.getErrorStream());
        proc.waitFor();
        System.out.println(command + " exitValue() " + proc.exitValue());
    }
    
    /**
     * Prints the output lines generated by the independent processes.
     * @param cmd string containing an identifier of the process
     * @param ins the input stream generated by the process
     * @throws Exception in case of some error occurs during the line fetching
     */
    private static void printLines(String cmd, InputStream ins) throws Exception {
        String line = null;
        BufferedReader in = new BufferedReader(new InputStreamReader(ins));
        while ((line = in.readLine()) != null) {
            System.out.println(cmd + " " + line);
        }
    }
    
}
