package entities;

import common.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author fp
 */
public class Server extends javax.swing.JFrame implements MessageProcessor {
    
    private int id;
    private final int port;
    private SocketServer socketServer;
    private Thread serverThread;
    private final String mainServerHost;
    private final Integer mainServerPort;

    /**
     * Creates new form Server
     */
    public Server(String args[]) {
        this.port = Integer.valueOf(args[0]);
        this.mainServerHost = args[1];
        this.mainServerPort = Integer.valueOf(args[2]);
        
        this.socketServer = new SocketServer(this.port, this);
        this.serverThread = new Thread(socketServer);
        this.serverThread.start();
        this.initManagerClient();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server(args).setVisible(true);
            }
        });
    }
    
    public void initManagerClient(){
        try {
            SocketClient socketManager = new SocketClient(this.mainServerHost, this.mainServerPort);
            socketManager.send("newServer-localhost-" + this.port);
            socketManager.close();
        } catch (IOException ex) {
            Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void processMessage(String message) {
        String[] processedMessage = message.split("-");
        switch(processedMessage[0]){
            case "serverId"://serverId-id
                this.id=Integer.valueOf(processedMessage[1]);
                this.setTitle("Server #" + this.id);
                break;
            case "healthcheck":// healthcheck
                break;
            case "request": //request-clientHost-clientPort-request
                SocketClient socketManager = new SocketClient(this.mainServerHost, this.mainServerPort);
                try {
                    socketManager.send("newRequest-"+this.id+"-" + processedMessage[3]);
                } catch (IOException ex) {
                    Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
                }
                socketManager.close();
                PiCalculation request = new PiCalculation(processedMessage[1], Integer.valueOf(processedMessage[2]),processedMessage[3]);
                Thread requestProcessing = new Thread(request);
                requestProcessing.start();
                break;

        }
    }
    
    private class PiCalculation implements Runnable{
        
        private String message;
        private String[] processedMessage;
        private final int clientPort;
        private final String clientHost;
        
        public PiCalculation(String clientHost, int clientPort, String message){
            this.message=message;
            this.processedMessage = message.split("|");
            for(String m: this.processedMessage) {
                m = m.trim();
            }
            this.clientHost=clientHost;
            this.clientPort=clientPort;
        }
        
        @Override
        public void run() {
            try {
                Thread.sleep(Integer.valueOf(this.processedMessage[3])*1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
            }

            String reply = "| " +id + " | " + this.processedMessage[0] + " | " + this.processedMessage[1] + " | 02 | " + this.processedMessage[3] + " | 3.1415 |";
            
            SocketClient targetClient = new SocketClient(clientHost, clientPort);
            try {
                targetClient.send(reply);
            } catch (IOException ex) {
                Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
            }
            targetClient.close();
            
            SocketClient socketManager = new SocketClient(mainServerHost, mainServerPort);
            try {
                socketManager.send("processedRequest-"+id+"-" + message);
            } catch (IOException ex) {
                Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
            }
            socketManager.close();
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
