package fi;

import fi.monitors.Standing;
import fi.monitors.Storehouse;
import fi.monitors.Path;
import fi.monitors.Granary;
import fi.workers.Farmer;
import fi.workers.CCProxy;
import common.SocketClient;
import common.SocketServer;
import javax.swing.JTextField;

/**
 * Class for the Farm Infrastructure for the agricultural harvest.
 * @author Filipe Pires (85122) and João Alegria (85048)
 */
public class FarmInfrastructure extends javax.swing.JFrame {
    
    private static SocketServer fiServer;
    private static SocketClient ccClient;
    
    private static MonitorMetadata metadata;
    private static final int teamSize = 5;
    private static final int pathSize = 10;
    
    private static Storehouse storeHouse;
    private static Standing standing;
    private static Path path;
    private static Granary granary;
    private static Farmer[] farmerTeam;
    private static CCProxy messageProcessor;

    /**
     * Creates new form NewJFrame
     */
    public FarmInfrastructure() {
        initComponents();
        
        metadata = new MonitorMetadata(teamSize);
        
        storeHouse = new Storehouse(this, metadata, teamSize);
        standing = new Standing(this, metadata);
        path = new Path(this, metadata, pathSize);
        granary = new Granary(this, metadata);
        
        farmerTeam = new Farmer[teamSize];
        for(int i=0; i<teamSize; i++) {
            Farmer f = new Farmer(i+1,storeHouse,standing,path,granary);
            f.start();
            farmerTeam[i] = f;
        }
        
        ccClient = new SocketClient("localhost",6666);
        messageProcessor = new CCProxy(ccClient, storeHouse, standing, path, granary);
        fiServer = new SocketServer(7777, messageProcessor);
        fiServer.start();
        ccClient.send("infrastructureServerOnline");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        storehousePanel = new javax.swing.JPanel();
        storehouseLabel = new javax.swing.JLabel();
        sh1 = new javax.swing.JTextField();
        sh3 = new javax.swing.JTextField();
        sh2 = new javax.swing.JTextField();
        sh5 = new javax.swing.JTextField();
        sh4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        standingAreaPanel = new javax.swing.JPanel();
        standingAreaLabel = new javax.swing.JLabel();
        sa1 = new javax.swing.JTextField();
        sa2 = new javax.swing.JTextField();
        sa3 = new javax.swing.JTextField();
        sa4 = new javax.swing.JTextField();
        sa5 = new javax.swing.JTextField();
        pathPanel = new javax.swing.JPanel();
        PathLabel = new javax.swing.JLabel();
        p01_1 = new javax.swing.JTextField();
        p01_2 = new javax.swing.JTextField();
        p01_3 = new javax.swing.JTextField();
        p01_4 = new javax.swing.JTextField();
        p01_5 = new javax.swing.JTextField();
        p02_1 = new javax.swing.JTextField();
        p02_2 = new javax.swing.JTextField();
        p02_3 = new javax.swing.JTextField();
        p02_4 = new javax.swing.JTextField();
        p02_5 = new javax.swing.JTextField();
        p03_1 = new javax.swing.JTextField();
        p03_2 = new javax.swing.JTextField();
        p03_3 = new javax.swing.JTextField();
        p03_4 = new javax.swing.JTextField();
        p03_5 = new javax.swing.JTextField();
        p04_1 = new javax.swing.JTextField();
        p04_2 = new javax.swing.JTextField();
        p04_3 = new javax.swing.JTextField();
        p04_4 = new javax.swing.JTextField();
        p04_5 = new javax.swing.JTextField();
        p05_1 = new javax.swing.JTextField();
        p05_2 = new javax.swing.JTextField();
        p05_3 = new javax.swing.JTextField();
        p05_4 = new javax.swing.JTextField();
        p05_5 = new javax.swing.JTextField();
        p06_1 = new javax.swing.JTextField();
        p06_2 = new javax.swing.JTextField();
        p06_3 = new javax.swing.JTextField();
        p06_4 = new javax.swing.JTextField();
        p06_5 = new javax.swing.JTextField();
        p07_1 = new javax.swing.JTextField();
        p07_2 = new javax.swing.JTextField();
        p07_3 = new javax.swing.JTextField();
        p07_4 = new javax.swing.JTextField();
        p07_5 = new javax.swing.JTextField();
        p08_1 = new javax.swing.JTextField();
        p08_2 = new javax.swing.JTextField();
        p08_3 = new javax.swing.JTextField();
        p08_4 = new javax.swing.JTextField();
        p08_5 = new javax.swing.JTextField();
        p09_1 = new javax.swing.JTextField();
        p09_2 = new javax.swing.JTextField();
        p09_3 = new javax.swing.JTextField();
        p09_4 = new javax.swing.JTextField();
        p09_5 = new javax.swing.JTextField();
        p10_1 = new javax.swing.JTextField();
        p10_2 = new javax.swing.JTextField();
        p10_3 = new javax.swing.JTextField();
        p10_4 = new javax.swing.JTextField();
        p10_5 = new javax.swing.JTextField();
        granaryPanel = new javax.swing.JPanel();
        granaryLabel = new javax.swing.JLabel();
        g4 = new javax.swing.JTextField();
        g5 = new javax.swing.JTextField();
        g1 = new javax.swing.JTextField();
        g2 = new javax.swing.JTextField();
        g3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setText("Farm Infrastructure");

        storehousePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        storehouseLabel.setText("Storehouse");

        sh1.setEnabled(false);

        sh3.setEnabled(false);

        sh2.setEnabled(false);

        sh5.setEnabled(false);

        sh4.setEnabled(false);

        jLabel1.setText("Corn Cobs");

        jTextField1.setText("0");
        jTextField1.setEnabled(false);

        javax.swing.GroupLayout storehousePanelLayout = new javax.swing.GroupLayout(storehousePanel);
        storehousePanel.setLayout(storehousePanelLayout);
        storehousePanelLayout.setHorizontalGroup(
            storehousePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(storehousePanelLayout.createSequentialGroup()
                .addGroup(storehousePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(storehousePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(storehouseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(storehousePanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(storehousePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sh4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sh5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sh2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sh3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sh1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(storehousePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)))
                .addContainerGap())
        );
        storehousePanelLayout.setVerticalGroup(
            storehousePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(storehousePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(storehouseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(storehousePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(storehousePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, storehousePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addComponent(sh1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sh2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sh3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sh4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sh5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        standingAreaPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        standingAreaLabel.setText("Standing Area");

        sa1.setEnabled(false);

        sa2.setEnabled(false);

        sa3.setEnabled(false);

        sa4.setEnabled(false);

        sa5.setEnabled(false);

        javax.swing.GroupLayout standingAreaPanelLayout = new javax.swing.GroupLayout(standingAreaPanel);
        standingAreaPanel.setLayout(standingAreaPanelLayout);
        standingAreaPanelLayout.setHorizontalGroup(
            standingAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(standingAreaPanelLayout.createSequentialGroup()
                .addGroup(standingAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(standingAreaPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(standingAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sa4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sa5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sa2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sa3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sa1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(standingAreaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(standingAreaLabel)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        standingAreaPanelLayout.setVerticalGroup(
            standingAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(standingAreaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(standingAreaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(sa1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sa2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sa3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sa4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sa5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pathPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        PathLabel.setText("Path");

        p01_1.setEnabled(false);

        p01_2.setEnabled(false);

        p01_3.setEnabled(false);

        p01_4.setEnabled(false);

        p01_5.setEnabled(false);

        p02_1.setEnabled(false);

        p02_2.setEnabled(false);

        p02_3.setEnabled(false);

        p02_4.setEnabled(false);

        p02_5.setEnabled(false);

        p03_1.setEnabled(false);

        p03_2.setEnabled(false);

        p03_3.setEnabled(false);

        p03_4.setEnabled(false);

        p03_5.setEnabled(false);

        p04_1.setEnabled(false);

        p04_2.setEnabled(false);

        p04_3.setEnabled(false);

        p04_4.setEnabled(false);

        p04_5.setEnabled(false);

        p05_1.setEnabled(false);

        p05_2.setEnabled(false);

        p05_3.setEnabled(false);

        p05_4.setEnabled(false);

        p05_5.setEnabled(false);

        p06_1.setEnabled(false);

        p06_2.setEnabled(false);

        p06_3.setEnabled(false);

        p06_4.setEnabled(false);

        p06_5.setEnabled(false);

        p07_1.setEnabled(false);

        p07_2.setEnabled(false);

        p07_3.setEnabled(false);

        p07_4.setEnabled(false);

        p07_5.setEnabled(false);

        p08_1.setEnabled(false);

        p08_2.setEnabled(false);

        p08_3.setEnabled(false);

        p08_4.setEnabled(false);

        p08_5.setEnabled(false);

        p09_1.setEnabled(false);

        p09_2.setEnabled(false);

        p09_3.setEnabled(false);

        p09_4.setEnabled(false);

        p09_5.setEnabled(false);

        p10_1.setEnabled(false);

        p10_2.setEnabled(false);

        p10_3.setEnabled(false);

        p10_4.setEnabled(false);

        p10_5.setEnabled(false);

        javax.swing.GroupLayout pathPanelLayout = new javax.swing.GroupLayout(pathPanel);
        pathPanel.setLayout(pathPanelLayout);
        pathPanelLayout.setHorizontalGroup(
            pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pathPanelLayout.createSequentialGroup()
                .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pathPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p01_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p01_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p01_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p01_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p01_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p02_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p02_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p02_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p02_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p02_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p03_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p03_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p03_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p03_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p03_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p04_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p04_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p04_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p04_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p04_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p05_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p05_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p05_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p05_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p05_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p06_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p06_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p06_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p06_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p06_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p07_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p07_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p07_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p07_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p07_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p08_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p08_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p08_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p08_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p08_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p09_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p09_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p09_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p09_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p09_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p10_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p10_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p10_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p10_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p10_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pathPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PathLabel)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        pathPanelLayout.setVerticalGroup(
            pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pathPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PathLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pathPanelLayout.createSequentialGroup()
                            .addComponent(p10_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p10_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p10_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p10_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p10_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pathPanelLayout.createSequentialGroup()
                            .addComponent(p09_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p09_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p09_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p09_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p09_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pathPanelLayout.createSequentialGroup()
                            .addComponent(p08_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p08_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p08_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p08_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p08_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pathPanelLayout.createSequentialGroup()
                            .addComponent(p07_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p07_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p07_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p07_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p07_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pathPanelLayout.createSequentialGroup()
                            .addComponent(p06_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p06_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p06_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p06_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p06_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pathPanelLayout.createSequentialGroup()
                            .addComponent(p05_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p05_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p05_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p05_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p05_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pathPanelLayout.createSequentialGroup()
                            .addComponent(p04_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p04_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p04_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p04_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p04_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pathPanelLayout.createSequentialGroup()
                            .addComponent(p03_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p03_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p03_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p03_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p03_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pathPanelLayout.createSequentialGroup()
                            .addComponent(p02_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p02_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p02_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p02_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p02_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pathPanelLayout.createSequentialGroup()
                            .addComponent(p01_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p01_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p01_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p01_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(p01_5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        granaryPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        granaryLabel.setText("Granary");

        g4.setEnabled(false);

        g5.setEnabled(false);

        g1.setEnabled(false);

        g2.setEnabled(false);

        g3.setEnabled(false);

        jTextField2.setText("0");
        jTextField2.setEnabled(false);

        jLabel2.setText("Corn Cobs");

        javax.swing.GroupLayout granaryPanelLayout = new javax.swing.GroupLayout(granaryPanel);
        granaryPanel.setLayout(granaryPanelLayout);
        granaryPanelLayout.setHorizontalGroup(
            granaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(granaryPanelLayout.createSequentialGroup()
                .addGroup(granaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(granaryPanelLayout.createSequentialGroup()
                        .addGroup(granaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(granaryPanelLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(granaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(g4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(granaryPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(granaryLabel)))
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(granaryPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)))
                .addContainerGap())
        );
        granaryPanelLayout.setVerticalGroup(
            granaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, granaryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(granaryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(granaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, granaryPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(g1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(g2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(g3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(g4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(g5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(storehousePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(standingAreaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pathPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(granaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(granaryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(storehousePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pathPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(standingAreaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        System.out.println("Initializing Farm Infrastructure... ");
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FarmInfrastructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FarmInfrastructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FarmInfrastructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FarmInfrastructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        try {
            
        } catch (Exception e) {
            e.printStackTrace();
        }finally{
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new FarmInfrastructure().setVisible(true);
                }
            });
        }
    }
    
    public void sendMessage(String message){
        this.ccClient.send(message);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PathLabel;
    private javax.swing.JTextField g1;
    private javax.swing.JTextField g2;
    private javax.swing.JTextField g3;
    private javax.swing.JTextField g4;
    private javax.swing.JTextField g5;
    private javax.swing.JLabel granaryLabel;
    private javax.swing.JPanel granaryPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField p01_1;
    private javax.swing.JTextField p01_2;
    private javax.swing.JTextField p01_3;
    private javax.swing.JTextField p01_4;
    private javax.swing.JTextField p01_5;
    private javax.swing.JTextField p02_1;
    private javax.swing.JTextField p02_2;
    private javax.swing.JTextField p02_3;
    private javax.swing.JTextField p02_4;
    private javax.swing.JTextField p02_5;
    private javax.swing.JTextField p03_1;
    private javax.swing.JTextField p03_2;
    private javax.swing.JTextField p03_3;
    private javax.swing.JTextField p03_4;
    private javax.swing.JTextField p03_5;
    private javax.swing.JTextField p04_1;
    private javax.swing.JTextField p04_2;
    private javax.swing.JTextField p04_3;
    private javax.swing.JTextField p04_4;
    private javax.swing.JTextField p04_5;
    private javax.swing.JTextField p05_1;
    private javax.swing.JTextField p05_2;
    private javax.swing.JTextField p05_3;
    private javax.swing.JTextField p05_4;
    private javax.swing.JTextField p05_5;
    private javax.swing.JTextField p06_1;
    private javax.swing.JTextField p06_2;
    private javax.swing.JTextField p06_3;
    private javax.swing.JTextField p06_4;
    private javax.swing.JTextField p06_5;
    private javax.swing.JTextField p07_1;
    private javax.swing.JTextField p07_2;
    private javax.swing.JTextField p07_3;
    private javax.swing.JTextField p07_4;
    private javax.swing.JTextField p07_5;
    private javax.swing.JTextField p08_1;
    private javax.swing.JTextField p08_2;
    private javax.swing.JTextField p08_3;
    private javax.swing.JTextField p08_4;
    private javax.swing.JTextField p08_5;
    private javax.swing.JTextField p09_1;
    private javax.swing.JTextField p09_2;
    private javax.swing.JTextField p09_3;
    private javax.swing.JTextField p09_4;
    private javax.swing.JTextField p09_5;
    private javax.swing.JTextField p10_1;
    private javax.swing.JTextField p10_2;
    private javax.swing.JTextField p10_3;
    private javax.swing.JTextField p10_4;
    private javax.swing.JTextField p10_5;
    private javax.swing.JPanel pathPanel;
    private javax.swing.JTextField sa1;
    private javax.swing.JTextField sa2;
    private javax.swing.JTextField sa3;
    private javax.swing.JTextField sa4;
    private javax.swing.JTextField sa5;
    private javax.swing.JTextField sh1;
    private javax.swing.JTextField sh2;
    private javax.swing.JTextField sh3;
    private javax.swing.JTextField sh4;
    private javax.swing.JTextField sh5;
    private javax.swing.JLabel standingAreaLabel;
    private javax.swing.JPanel standingAreaPanel;
    private javax.swing.JLabel storehouseLabel;
    private javax.swing.JPanel storehousePanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    
    public void presentFarmerInStorehouse(int farmerId, int position) {
        switch(position) {
            case 0:
                sh1.setText(""+farmerId);
                break;
            case 1:
                sh2.setText(""+farmerId);
                break;
            case 2:
                sh3.setText(""+farmerId);
                break;
            case 3:
                sh4.setText(""+farmerId);
                break;
            case 4:
                sh5.setText(""+farmerId);
                break;
        }
    }
    
    public JTextField getG1() {
        return g1;
    }

    public JTextField getG2() {
        return g2;
    }

    public JTextField getG3() {
        return g3;
    }

    public JTextField getG4() {
        return g4;
    }

    public JTextField getG5() {
        return g5;
    }

    public JTextField getP01_1() {
        return p01_1;
    }

    public JTextField getP01_2() {
        return p01_2;
    }

    public JTextField getP01_3() {
        return p01_3;
    }

    public JTextField getP01_4() {
        return p01_4;
    }

    public JTextField getP01_5() {
        return p01_5;
    }

    public JTextField getP02_1() {
        return p02_1;
    }

    public JTextField getP02_2() {
        return p02_2;
    }

    public JTextField getP02_3() {
        return p02_3;
    }

    public JTextField getP02_4() {
        return p02_4;
    }

    public JTextField getP02_5() {
        return p02_5;
    }

    public JTextField getP03_1() {
        return p03_1;
    }

    public JTextField getP03_2() {
        return p03_2;
    }

    public JTextField getP03_3() {
        return p03_3;
    }

    public JTextField getP03_4() {
        return p03_4;
    }

    public JTextField getP03_5() {
        return p03_5;
    }

    public JTextField getP04_1() {
        return p04_1;
    }

    public JTextField getP04_2() {
        return p04_2;
    }

    public JTextField getP04_3() {
        return p04_3;
    }

    public JTextField getP04_4() {
        return p04_4;
    }

    public JTextField getP04_5() {
        return p04_5;
    }

    public JTextField getP05_1() {
        return p05_1;
    }

    public JTextField getP05_2() {
        return p05_2;
    }

    public JTextField getP05_3() {
        return p05_3;
    }

    public JTextField getP05_4() {
        return p05_4;
    }

    public JTextField getP05_5() {
        return p05_5;
    }

    public JTextField getP06_1() {
        return p06_1;
    }

    public JTextField getP06_2() {
        return p06_2;
    }

    public JTextField getP06_3() {
        return p06_3;
    }

    public JTextField getP06_4() {
        return p06_4;
    }

    public JTextField getP06_5() {
        return p06_5;
    }

    public JTextField getP07_1() {
        return p07_1;
    }

    public JTextField getP07_2() {
        return p07_2;
    }

    public JTextField getP07_3() {
        return p07_3;
    }

    public JTextField getP07_4() {
        return p07_4;
    }

    public JTextField getP07_5() {
        return p07_5;
    }

    public JTextField getP08_1() {
        return p08_1;
    }

    public JTextField getP08_2() {
        return p08_2;
    }

    public JTextField getP08_3() {
        return p08_3;
    }

    public JTextField getP08_4() {
        return p08_4;
    }

    public JTextField getP08_5() {
        return p08_5;
    }

    public JTextField getP09_1() {
        return p09_1;
    }

    public JTextField getP09_2() {
        return p09_2;
    }

    public JTextField getP09_3() {
        return p09_3;
    }

    public JTextField getP09_4() {
        return p09_4;
    }

    public JTextField getP09_5() {
        return p09_5;
    }

    public JTextField getP10_1() {
        return p10_1;
    }

    public JTextField getP10_2() {
        return p10_2;
    }

    public JTextField getP10_3() {
        return p10_3;
    }

    public JTextField getP10_4() {
        return p10_4;
    }

    public JTextField getP10_5() {
        return p10_5;
    }

    public JTextField getSa1() {
        return sa1;
    }

    public JTextField getSa2() {
        return sa2;
    }

    public JTextField getSa3() {
        return sa3;
    }

    public JTextField getSa4() {
        return sa4;
    }

    public JTextField getSa5() {
        return sa5;
    }

    public JTextField getSh1() {
        return sh1;
    }

    public JTextField getSh2() {
        return sh2;
    }

    public JTextField getSh3() {
        return sh3;
    }

    public JTextField getSh4() {
        return sh4;
    }

    public JTextField getSh5() {
        return sh5;
    }

}
